let timer;
let isRunning = false;
let timeLeft = 25 * 60;
let isBreakTime = false;
let workDuration = 25 * 60;
let shortBreakDuration = 5 * 60;
let longBreakDuration = 10 * 60;
let sessionCount = 0;

const sprites = [
    "https://img.pokemondb.net/sprites/black-white/anim/normal/bulbasaur.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/bulbasaur.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/ivysaur.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/ivysaur.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/venusaur.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/venusaur.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/charmander.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/charmander.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/charmeleon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/charmeleon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/charizard.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/charizard.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/squirtle.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/squirtle.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/wartortle.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/wartortle.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/blastoise.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/blastoise.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/caterpie.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/caterpie.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/metapod.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/metapod.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/butterfree.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/butterfree.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/weedle.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/weedle.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/kakuna.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/kakuna.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/beedrill.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/beedrill.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/pidgey.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/pidgey.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeotto.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/pidgeotto.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/pidgeot.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/pidgeot.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/rattata.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/rattata.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/raticate.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/raticate.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/spearow.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/spearow.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/fearow.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/fearow.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/ekans.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/ekans.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/arbok.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/arbok.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/pikachu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/pikachu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/raichu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/raichu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/sandshrew.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/sandshrew.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/sandslash.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/sandslash.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/nidoran-f.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/nidoran-f.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/nidorina.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/nidorina.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/nidoqueen.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/nidoqueen.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/nidoran-m.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/nidoran-m.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/nidorino.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/nidorino.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/nidoking.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/nidoking.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/clefairy.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/clefairy.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/clefable.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/clefable.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/vulpix.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/vulpix.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/ninetales.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/ninetales.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/jigglypuff.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/jigglypuff.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/wigglytuff.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/wigglytuff.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/zubat.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/zubat.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/golbat.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/golbat.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/oddish.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/oddish.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/gloom.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/gloom.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/vileplume.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/vileplume.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/paras.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/paras.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/parasect.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/parasect.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/venonat.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/venonat.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/venomoth.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/venomoth.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/diglett.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/diglett.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/dugtrio.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/dugtrio.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/meowth.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/meowth.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/persian.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/persian.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/psyduck.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/psyduck.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/golduck.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/golduck.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/mankey.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/mankey.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/primeape.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/primeape.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/growlithe.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/growlithe.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/arcanine.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/arcanine.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/poliwag.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/poliwag.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/poliwhirl.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/poliwhirl.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/poliwrath.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/poliwrath.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/abra.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/abra.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/kadabra.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/kadabra.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/alakazam.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/alakazam.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/machop.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/machop.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/machoke.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/machoke.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/machamp.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/machamp.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/bellsprout.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/bellsprout.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/weepinbell.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/weepinbell.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/victreebel.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/victreebel.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/geodude.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/geodude.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/graveler.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/graveler.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/golem.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/golem.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/ponyta.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/ponyta.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/rapidash.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/rapidash.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/slowpoke.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/slowpoke.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/slowbro.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/slowbro.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/magnemite.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/magnemite.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/magneton.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/magneton.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/farfetchd.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/farfetchd.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/doduo.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/doduo.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/dodrio.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/dodrio.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/seel.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/seel.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/dewgong.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/dewgong.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/grimer.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/grimer.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/muk.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/muk.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/shellder.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/shellder.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/cloyster.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/cloyster.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/gastly.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/gastly.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/haunter.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/haunter.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/gengar.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/gengar.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/onix.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/onix.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/drowzee.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/drowzee.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/hypno.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/hypno.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/krabby.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/krabby.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/kingler.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/kingler.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/voltorb.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/voltorb.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/electrode.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/electrode.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/exeggcute.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/exeggcute.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/exeggutor.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/exeggutor.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/cubone.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/cubone.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/marowak.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/marowak.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonlee.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/hitmonlee.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/hitmonchan.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/hitmonchan.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/lickitung.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/lickitung.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/koffing.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/koffing.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/weezing.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/weezing.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/rhyhorn.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/rhyhorn.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/rhydon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/rhydon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/chansey.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/chansey.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/tangela.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/tangela.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/kangaskhan.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/kangaskhan.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/horsea.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/horsea.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/seadra.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/seadra.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/goldeen.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/goldeen.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/seaking.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/seaking.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/staryu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/staryu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/starmie.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/starmie.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/mrmime.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/mrmime.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/scyther.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/scyther.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/jynx.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/jynx.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/electabuzz.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/electabuzz.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/magmar.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/magmar.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/pinsir.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/pinsir.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/tauros.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/tauros.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/magikarp.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/magikarp.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/gyarados.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/gyarados.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/lapras.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/lapras.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/ditto.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/ditto.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/eevee.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/eevee.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/vaporeon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/vaporeon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/jolteon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/jolteon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/flareon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/flareon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/porygon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/porygon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/omanyte.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/omanyte.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/omastar.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/omastar.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/kabuto.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/kabuto.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/kabutops.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/kabutops.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/aerodactyl.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/aerodactyl.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/snorlax.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/snorlax.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/articuno.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/articuno.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/zapdos.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/zapdos.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/moltres.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/moltres.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/dratini.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/dratini.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/dragonair.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/dragonair.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/dragonite.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/dragonite.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/mewtwo.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/mewtwo.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/mew.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/mew.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/lucario.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/lucario.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/greninja.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/greninja.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/garchomp.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/garchomp.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/gardevoir.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/gardevoir.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/charizard.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/charizard.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/pikachu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/pikachu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/chikorita.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/chikorita.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/bayleef.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/bayleef.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/meganium.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/meganium.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/cyndaquil.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/cyndaquil.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/quilava.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/quilava.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/typhlosion.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/typhlosion.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/totodile.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/totodile.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/croconaw.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/croconaw.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/feraligatr.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/feraligatr.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/sentret.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/sentret.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/furret.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/furret.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/hoothoot.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/hoothoot.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/noctowl.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/noctowl.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/ledyba.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/ledyba.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/ledian.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/ledian.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/spinarak.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/spinarak.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/ariados.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/ariados.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/crobat.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/crobat.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/chinchou.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/chinchou.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/lanturn.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/lanturn.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/pichu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/pichu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/cleffa.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/cleffa.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/igglybuff.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/igglybuff.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/togepi.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/togepi.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/togetic.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/togetic.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/natu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/natu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/xatu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/xatu.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/mareep.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/mareep.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/flaaffy.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/flaaffy.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/ampharos.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/ampharos.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/bellossom.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/bellossom.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/marill.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/marill.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/azumarill.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/azumarill.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/sudowoodo.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/sudowoodo.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/politoed.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/politoed.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/hoppip.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/hoppip.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/skiploom.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/skiploom.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/jumpluff.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/jumpluff.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/aipom.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/aipom.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/sunkern.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/sunkern.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/sunflora.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/sunflora.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/yanma.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/yanma.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/wooper.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/wooper.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/quagsire.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/quagsire.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/espeon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/espeon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/umbreon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/umbreon.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/murkrow.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/murkrow.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/slowking.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/slowking.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/misdreavus.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/misdreavus.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/unown.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/unown.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/wobbuffet.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/wobbuffet.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/girafarig.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/girafarig.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/pineco.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/pineco.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/forretress.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/forretress.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/dunsparce.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/dunsparce.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/gligar.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/gligar.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/steelix.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/steelix.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/snubbull.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/snubbull.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/granbull.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/granbull.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/qwilfish.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/qwilfish.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/scizor.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/scizor.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/shuckle.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/shuckle.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/heracross.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/heracross.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/sneasel.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/sneasel.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/teddiursa.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/teddiursa.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/ursaring.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/ursaring.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/slugo.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/slugo.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/magcargo.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/magcargo.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/swinub.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/swinub.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/piloswine.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/piloswine.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/corsola.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/corsola.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/remoraid.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/remoraid.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/octillery.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/octillery.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/delibird.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/delibird.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/mantine.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/mantine.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/skarmory.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/skarmory.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/houndour.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/houndour.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/houndoom.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/houndoom.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/kingdra.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/kingdra.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/phanpy.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/phanpy.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/donphan.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/donphan.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/porygon2.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/porygon2.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/stantler.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/stantler.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/smeargle.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/smeargle.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/tyrogue.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/tyrogue.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/hitmontop.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/hitmontop.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/smoochum.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/smoochum.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/elekid.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/elekid.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/magby.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/magby.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/miltank.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/miltank.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/blissey.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/blissey.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/raikou.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/raikou.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/entei.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/entei.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/normal/suicune.gif",
    "https://img.pokemondb.net/sprites/black-white/anim/shiny/suicune.gif"
];
 
document.addEventListener('DOMContentLoaded', function () {
    // Get DOM elements
    const timeDisplay = document.getElementById('time-display');
    const startButton = document.getElementById('start-btn');
    const resetButton = document.getElementById('reset-btn');
    const darkModeButton = document.getElementById('darkmode-btn');
    const statusDisplay = document.getElementById('status');
    const workTimeInput = document.getElementById('work-time');
    const shortBreakInput = document.getElementById('short-break-time');
    const longBreakInput = document.getElementById('long-break-time');
    const spriteImg = document.querySelector('.sprite');

    // Initialize state
    let isRunning = false;
    let timeLeft = 25 * 60; // 25 minutes in seconds

    function updateSprite() {
        const randomIndex = Math.floor(Math.random() * sprites.length);
        spriteImg.src = sprites[randomIndex];
    }

    function updateDisplay() {
        const minutes = Math.floor(timeLeft / 60);
        const seconds = timeLeft % 60;
        document.getElementById('minutes').textContent = String(minutes).padStart(2, '0');
        document.getElementById('seconds').textContent = String(seconds).padStart(2, '0');
        startButton.textContent = isRunning ? 'Pause' : 'Start';
        statusDisplay.textContent = isBreakTime ? 'Break Time' : 'Work Time';
    }

    function toggleTimer() {
        if (!isRunning) {
            chrome.runtime.sendMessage({ action: 'startTimer' });
            startButton.textContent = 'Pause';
        } else {
            chrome.runtime.sendMessage({ action: 'pauseTimer' });
            startButton.textContent = 'Start';
        }
        isRunning = !isRunning;
    }

    function resetTimer() {
        chrome.runtime.sendMessage({ action: 'resetTimer' });
        isRunning = false;
        timeLeft = 25 * 60; // Reset local timeLeft
        updateDisplay(); // Update display immediately
        updateSprite();
        startButton.textContent = 'Start'; // Reset button text
    }

    function toggleDarkMode() {
        document.body.classList.toggle('dark-mode');
        localStorage.setItem('darkMode', document.body.classList.contains('dark-mode'));
    }

    // Initialize sprite and dark mode
    updateSprite();
    if (localStorage.getItem('darkMode') === 'true') {
        document.body.classList.add('dark-mode');
    }

    // Get initial state from background
    chrome.runtime.sendMessage({ action: 'getState' }, (response) => {
        if (response) {
            isRunning = response.isRunning;
            timeLeft = response.timeLeft;
            isBreakTime = response.isBreakTime;
            sessionCount = response.sessionCount;
            workDuration = response.workDuration;
            shortBreakDuration = response.shortBreakDuration;
            longBreakDuration = response.longBreakDuration;
            updateDisplay();
        }
    });

    // Listen for timer updates
    chrome.runtime.onMessage.addListener((message) => {
        if (message.action === 'tick') {
            timeLeft = message.timeLeft;
            isBreakTime = message.isBreakTime;
            updateDisplay();
        }
    });

    // Add event listeners
    startButton.addEventListener('click', toggleTimer);
    resetButton.addEventListener('click', resetTimer);
    darkModeButton.addEventListener('click', toggleDarkMode);

    workTimeInput.addEventListener('change', function () {
        workDuration = workTimeInput.value * 60;
        if (!isRunning && !isBreakTime) {
            timeLeft = workDuration;
            updateTimeDisplay();
        }
    });

    shortBreakInput.addEventListener('change', function () {
        shortBreakDuration = shortBreakInput.value * 60;
    });

    longBreakInput.addEventListener('change', function () {
        longBreakDuration = longBreakInput.value * 60;
    });

    updateTimeDisplay();
    updateSprite();
});